# Virtual Parking Sensor - top level Makefile
#
#   make setup           install compiler and kernel headers (Ubuntu/Debian or Fedora)
#   make                 build driver, application and tests
#   make load            insert the kernel module   (START=<cm> optional)
#   make run             start the dashboard application
#   make test            run unit + integration tests (module must be loaded)
#   make unload          remove the kernel module
#   make logs            show the driver's kernel log messages
#   make evidence        build, load, test, run a demo and save all output
#                        to docs/test-results/
#   make publish         make evidence, then commit and push the results
#   make clean           remove all build artefacts

SHELL   := /bin/bash
MODULE  := parking_sensor
RESULTS := docs/test-results

all: driver app tests

setup:
	@if command -v apt-get >/dev/null; then \
		sudo apt-get update && \
		sudo apt-get install -y build-essential git linux-headers-$$(uname -r); \
	elif command -v dnf >/dev/null; then \
		sudo dnf install -y gcc gcc-c++ make git kernel-devel-$$(uname -r) elfutils-libelf-devel; \
	else \
		echo "Please install gcc, g++, make and the kernel headers manually"; exit 1; \
	fi

driver:
	$(MAKE) -C driver

app:
	$(MAKE) -C app

tests: app
	$(MAKE) -C tests

load: driver
	sudo insmod driver/$(MODULE).ko $(if $(START),start_distance=$(START))
	@udevadm settle 2>/dev/null || sleep 1
	@ls -l /dev/parksensor

unload:
	sudo rmmod $(MODULE)

reload:
	-sudo rmmod $(MODULE)
	$(MAKE) load

run: app
	./app/parking_monitor

unit: tests
	$(MAKE) -C tests unit

integration: tests
	$(MAKE) -C tests integration

test: unit integration

logs:
	sudo dmesg | grep parksensor | tail -n 30

evidence:
	rm -rf $(RESULTS) && mkdir -p $(RESULTS)
	{ date; uname -a; g++ --version | head -n1; cat /etc/os-release | grep PRETTY_NAME; } > $(RESULTS)/00_environment.txt
	set -o pipefail; $(MAKE) --no-print-directory all 2>&1 | tee $(RESULTS)/01_build.txt
	-@sudo rmmod $(MODULE) 2>/dev/null
	sudo insmod driver/$(MODULE).ko
	@udevadm settle 2>/dev/null || sleep 1
	{ set -x; ls -l /dev/parksensor; cat /dev/parksensor; echo "dist 60" > /dev/parksensor; \
	  cat /dev/parksensor; echo "mode reverse" > /dev/parksensor; sleep 1; cat /dev/parksensor; \
	  echo "reset" > /dev/parksensor; cat /dev/parksensor; echo "dist 999" > /dev/parksensor; \
	  cat /proc/parksensor; } > $(RESULTS)/02_driver_shell.txt 2>&1 || true
	-set -o pipefail; ./tests/unit_tests 2>&1 | tee $(RESULTS)/03_unit_tests.txt
	-set -o pipefail; ./tests/driver_tests 2>&1 | tee $(RESULTS)/04_driver_tests.txt
	echo reset > /dev/parksensor
	printf '1\n2\n9\n10\n0\n' | ./app/parking_monitor --no-color --log $(RESULTS)/demo_log.txt \
		> $(RESULTS)/05_dashboard_demo.txt 2>&1
	sudo dmesg | grep parksensor | tail -n 60 > $(RESULTS)/06_kernel_log.txt
	sudo rmmod $(MODULE)
	{ echo "after rmmod:"; ls /dev/parksensor /proc/parksensor 2>&1; \
	  lsmod | grep $(MODULE) || echo "module not loaded"; } > $(RESULTS)/07_unload.txt || true
	{ echo "# Test Results"; echo; \
	  echo "Generated by \`make evidence\` on $$(date '+%Y-%m-%d %H:%M') - kernel $$(uname -r)"; echo; \
	  echo "| Suite | Result |"; echo "|---|---|"; \
	  echo "| Unit tests | $$(tail -n1 $(RESULTS)/03_unit_tests.txt) |"; \
	  echo "| Driver integration tests | $$(tail -n1 $(RESULTS)/04_driver_tests.txt) |"; echo; \
	  echo "| File | Content |"; echo "|---|---|"; \
	  echo "| [00_environment.txt](00_environment.txt) | OS, kernel, compiler |"; \
	  echo "| [01_build.txt](01_build.txt) | build output |"; \
	  echo "| [02_driver_shell.txt](02_driver_shell.txt) | driver used from the shell |"; \
	  echo "| [03_unit_tests.txt](03_unit_tests.txt) | unit tests |"; \
	  echo "| [04_driver_tests.txt](04_driver_tests.txt) | integration tests |"; \
	  echo "| [05_dashboard_demo.txt](05_dashboard_demo.txt) | dashboard: reading, reverse parking + auto-brake, /proc, log |"; \
	  echo "| [06_kernel_log.txt](06_kernel_log.txt) | kernel log (dmesg) |"; \
	  echo "| [07_unload.txt](07_unload.txt) | clean unload check |"; \
	  echo "| [demo_log.txt](demo_log.txt) | application event log |"; \
	} > $(RESULTS)/README.md
	@echo; cat $(RESULTS)/README.md

publish: evidence
	git add $(RESULTS) && git commit -m "test: add test results from $$(uname -r)" && git push

clean:
	$(MAKE) -C driver clean
	$(MAKE) -C app clean
	$(MAKE) -C tests clean

.PHONY: all setup driver app tests load unload reload run unit integration test logs evidence publish clean
